PostgreSQL:
  restart: always
  image: sameersbn/postgresql:10-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=guiborges
    - DB_PASS=root
    - DB_NAME=xyInc
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
