PostgreSQL:
  restart: always
  image: sameersbn/postgresql:10-2
  ports:
    - "5433:5432"
  environment:
    - DEBUG=false
    - DB_USER=guiborges
    - DB_PASS=root
    - DB_NAME=xyInc
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
    - ./src/main/resources/dumpDb.sql:/docker-entrypoint-initdb.d/dump.sql
