spring:
#DATABASE
  datasource:
    url: jdbc:h2:mem:xy-inc
    driverClassName: org.h2.Driver
    username: guiborges
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
jpa-show-sql: true
