spring:
  data:
    database: POSTGRES

#DATABASE
  datasource:
    url: jdbc:postgresql://localhost:5433/xyInc?createDataBaseIfNotExist=true&useSSL=false
    username: guiborges
    password: root

jpa-show-sql: true
